In [2]:
import pandas as pd

In [3]:
#cloning git
!git clone https://github.com/dorianb04/airline-ucg

Cloning into 'airline-ucg'...

In [3]:
companies = ['air-france', 'asiana-airlines', 'british-airways', 'iberia', 'japan-airlines-jal', 'lufthansa',
             'or520-emirates', 'or1030-korean-air', 'qatar-airways', 'ryanair' ,'singapore_airlines', 
             'swiss-international-air-lines-swiss','turkish-airlines']

numeric_columns = ['legroom_rating', 'seat_comfort_rating', 'entertainment_rating',
                   'customer_service_rating', 'value_rating', 'cleanliness_rating',
                   'check_in_rating', 'food_rating']

In [6]:
def clean_data(csv, i):
    df = pd.read_csv(csv)
    df = df.dropna(subset=['review_text', 'rating'])     # delete lines where review text or rating is empty 
    df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean()) # replace the missing values with the mean of the column
    df['travel_date'] = pd.to_datetime(df['travel_date'], format='%B %Y', errors='coerce') # convert the date columns to datetime
    df['travel_date'] = pd.to_datetime(df['travel_date'], errors='coerce')
    df['travel_date'] = df['travel_date'].dt.to_period('M')  # Conserve uniquement mois et annÃ©e
    df['review_date'] = pd.to_datetime(df['review_date'], format='%B %d, %Y', errors='coerce')
    df = df.dropna(subset=['travel_date', 'review_date']) # delete lines where travel date or review date is empty
    df = df.drop_duplicates(subset=['review_text', 'review_date'], keep='first') # delete duplicates
    df = df[(df['rating'] >= 0) & (df['rating'] <= 5)]  # delete lines where rating is not between 0 and 5
    df.to_csv('airline-ucg/cleaning/cleaned_data_csv/'+companies[i]+'_reviews_cleaned.csv', index=False)
    return df

In [7]:
for i in range(len(companies)):
    csv = 'airline-ucg/crawling/data_csv/'+companies[i]+'_reviews.csv'
    clean_data(csv, i)

In [59]:
df = pd.read_csv('airline-ucg/crawling/cleaned_data/'+companies[0]+'_reviews_cleaned.csv')
df.head()

,title,departure,destination,type_of_route,review_text,travel_date,review_date,rating,legroom_rating,seat_comfort_rating,entertainment_rating,customer_service_rating,value_rating,cleanliness_rating,check_in_rating,food_rating
0,Never travel with Air France,Vancouver,New Delhi,International,Worst Airline.stopped for door repair about 4 ...,2024-12,2024-12-21,1.0,1.000000,2.000000,1.000000,1.00000,1.000000,2.000000,1.000000,1.000000
1,Terrible service,Chicago,Paris,International,I boarded Air France on the 19th of December 2...,2024-12,2024-12-20,1.0,3.256587,3.118512,3.121919,3.08162,2.932936,3.497865,3.217346,3.081991
2,Traumatic,London,Algiers,International,A truly traumatic experience! So much that I g...,2024-08,2024-12-19,2.0,1.000000,1.000000,1.000000,2.00000,1.000000,1.000000,1.000000,1.000000
3,"Air France, the airline that keeps loosing lu...",London,Paris,Europe,Air France is quickly becoming the airline for...,2024-12,2024-12-19,3.0,3.000000,3.000000,3.000000,4.00000,3.000000,4.000000,3.000000,4.000000
4,^^^^ Take Me Home AF ^^^^,Vancouver,Manchester,International,We had surprisingly smooth flight with Air ...,2024-12,2024-12-19,4.0,4.000000,3.118512,4.000000,4.00000,4.000000,4.000000,4.000000,3.000000